### ISSUE TITLE
Unable to communicate with CA on Saas with connection profile

### ISSUE THREAD

**Issue by davidkel** [IBM-Blockchain/ansible-role-blockchain-platform-manager#152]
When trying to interact with the CA you get the error 

```
Error: Calling register endpoint failed with error [Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}]
    at ClientRequest.<anonymous> (/Users/sofia/Desktop/project/we.trade2.0/trade-network/app/smart-contract/node_modules/fabric-ca-client/lib/FabricCAClient.js:354:12)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The TLS root cert info is stored for the CA in this property as follows
```
            "tlsCACerts": {
                "pem": "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----"
```
the ca definition in this case I don't think uses that field. It expects the info to be in httpOptions under the trustedRoots definition. 
trustedRoots is an array of pem encoded root certs, so think the gateway needs to change as follows for the ca definition
```
"httpOptions: {
   "trustedRoots": ["-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----"]
}
```
I haven't actually had a chance to test that this is actually correct but it's what I think should work.

**Comment by davidkel** [comment]
The tlsCACerts field is correctly loaded into trustedRoots but the problem still occurs implying that self signed certs cannot be used and so in this scenario verify needs to be set to false. Not sure how ansible will know if a certificate is self-signed or not so may need to have the ability to set verify to false in the playbook.

**Comment by davidkel** [comment]
On further investigation it looks like the tls cert provided by ansible for the CA is not correct.
